spring:
  application:
    name: ayaka-spring-boot-starter

ayaka:
  ws:
    client:
      enable: false
      url: ws://127.0.0.1:5800
    server:
      enable: false
      url: /ws/ayaka
  http:
    enable: true
    endpoint: /ayaka
    api-port: 5800
    secret: U1FfRzMxQkVvRjBBZ0g5N25tS3Z1YlR3T1NTd0xHNk0=

  plugin:
    plugin-package: io.github.qingshu.ayaka.plugin