spring:
  application:
    name: ayaka-spring-boot-starter
ayaka:
  ws:
    server:
      enable: false
    client:
      enable: true
      url: "ws://192.168.1.9:5800"
  task:
    enable-async: true
    thread-name-prefix: "ayaka-async-task"
  plugin:
    plugin-package: "io.github.qingshu.ayaka.plugin"
