spring:
  application:
    name: ayaka-spring-boot-starter
ayaka:
  ws:
    server:
      enable: true
    client:
      enable: false
  task:
    enable-async: true
    thread-name-prefix: "ayaka-async-task"
  plugin:
    plugin-package: "io.github.qingshu.ayaka.plugin"
