name: Publish to Github Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradle build

      - name: Publish to Github Packages
        run: ./gradle publishMavenJavaPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secres.TOKEN }}